server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: vbs-backend
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 105MB

# JWT Configuration
jwt:
  # Secret key (at least 256-bit base64/hex string for HMAC-SHA256)
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration-ms: 86400000 # 24 hours

# Swagger OpenAPI Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
